---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stage-mf-swhurl-website
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: stage-mf-swhurl-website
      containers:
      - image: swhurl/mf-website:847ed45a4647f711d1ccc2bdc4a38fdc0e15f56c
        name: stage-mf-swhurl-website
